### ISSUE TITLE
[New Component] a checkbox component

### ISSUE THREAD

**Issue by kr-anurag** [avneesh0612/Orbits-UI#14]

**Comment by diganta413** [comment]
Can I work on this?

**Comment by kr-anurag** [comment]
sure!!

**Comment by diganta413** [comment]
Hey @kr-anurag @avneesh0612 can I use a external stylesheet for the checkbox component?
I am actually trying to make a custom checkbox using tailwind, but that needs to have a external stylesheet.

**Comment by kr-anurag** [comment]
> Hey @kr-anurag @avneesh0612 can I use a external stylesheet for the checkbox component? I am actually trying to make a custom checkbox using tailwind, but that needs to have a external stylesheet.

sure yep!
