### ISSUE TITLE
[FEAT] commitlint and the use of conventional commits for commit messages

### ISSUE THREAD

**Issue by AnishDe12020** [avneesh0612/Orbits-UI#17]
### Describe the feature

commit messages must be linted by commitlint so that they follow the conventional commits convention

### Is your feature request related to a problem? Please describe.

Changelogs cannot be generated automatically and various other issues arise due to no convention for the commit messages

### Describe the solution you'd like

Adding commitlint to lint commit messages

### Describe alternatives you've considered

None

**Comment by avneesh0612** [comment]
Fixed this issue!
