### ISSUE TITLE
[FEAT] display contributors list in the README

### ISSUE THREAD

**Issue by kr-anurag** [avneesh0612/Orbits-UI#26]
### Describe the feature

The README file should have a list of all contributors including their Profile Pic and name

### Describe the solution you'd like

Maybe we can set up a GitHub action for this.

### Describe alternatives you've considered

Or else, we can do it manually for now.

**Comment by kr-anurag** [comment]
@avneesh0612 we can use [all contributors bot](https://github.com/all-contributors/app) for this!

**Comment by avneesh0612** [comment]
yeahhh cool!

**Comment by kr-anurag** [comment]
@avneesh0612 we can close this issue now!
