### ISSUE TITLE
[DOCS] add anish de to the contributors list

### ISSUE THREAD

**Issue by kr-anurag** [avneesh0612/Orbits-UI#29]
### What would you like to share?

add anish de to the contributors list

**Comment by kr-anurag** [comment]
@all-contributors please add @AnishDe12020 for code and docs

**Comment by kr-anurag** [comment]
> @kr-anurag
> 
> We had trouble processing your request. Please try again later.

sure! go die!

**Comment by avneesh0612** [comment]
Lol

**Comment by avneesh0612** [comment]
@all-contributors please add @AnishDe12020 for code and docs
